name: build-image

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      env:
        required: true
        type: string
    secrets:
      GH_ACCESS_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm run build:${{ inputs.env }} --if-present
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.artifact_name }}
        path: build/*
