name: deploy

on:
  workflow_call:
    inputs:
      namespace:
        description: "Namespace"
        default: "default"
        type: string
      service:
        description: "Service name"
        required: true
        type: string
      container:
        description: "Container name"
        required: true
        type: string
      image:
        description: "Image to deploy"
        required: true
        type: string
      tag:
        description: "Image to deploy"
        required: true
        type: string
    secrets:
      DOCKER_REGISTRY:
        required: true
      KUBE_CONFIG:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate Google
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: bloock-cluster-dev-44ca8f9 
      -
        name: Set image
        run: |
          DEPLOYMENT=`kubectl get deployments -n ${{ inputs.namespace }} -l service=${{ inputs.service }} --output 'jsonpath={.items[0].metadata.name}'`
          kubectl set image --record deployment/$DEPLOYMENT ${{ inputs.container }}=${{ secrets.DOCKER_REGISTRY }}/${{ inputs.image }}:${{ inputs.tag }} -n ${{ inputs.namespace }}
          kubectl rollout status deployment/$DEPLOYMENT -n ${{ inputs.namespace }}
