name: deploy

on:
  workflow_call:
    inputs:
      artifact:
        description: "Artifact name"
        required: true
        type: string
      has_cdn:
        description: "Flag to indicate if the website has an enabled CDN endpoint"
        default: false
        type: boolean
    secrets:
      GOOGLE_CREDENTIALS:
        required: true
      GOOGLE_STORAGE_NAME:
        required: true
      GOOGLE_LOAD_BALANCER_NAME:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: ${{ inputs.artifact }}

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Upload files"
        run: gsutil -m rsync -R -d ./${{inputs.artifact}} gs://${{secrets.GOOGLE_STORAGE_NAME}}

      - name: "Invalidate cache"
        run: gcloud compute url-maps invalidate-cdn-cache ${{secrets.GOOGLE_LOAD_BALANCER_NAME}} --path "/*"
        if: ${{ inputs.has_cdn }}
