name: deploy

on:
  workflow_call:
    inputs:
      namespace:
        description: "Namespace"
        default: "default"
        type: string
      service:
        description: "Service name"
        required: true
        type: string
      container:
        description: "Container name"
        required: true
        type: string
      image:
        description: "Image to deploy"
        required: true
        type: string
      tag:
        description: "Image to deploy"
        required: true
        type: string
      environment:
        description: "Environment to deploy"
        required: true
        type: string
    secrets:
      DOCKER_REGISTRY:
        required: true
      GOOGLE_CREDENTIALS:
        required: true
      GOOGLE_CLUSTER_NAME:
        required: true
      GOOGLE_PROJECT_ID:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate Google
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GOOGLE_CLUSTER_NAME }}
          location: europe-west1 
      -
        name: Set image
        run: |
          DEPLOYMENT=`kubectl get deployments -n ${{ inputs.namespace }} -l service=${{ inputs.service }} --output 'jsonpath={.items[0].metadata.name}'`
          kubectl set image --record deployment/$DEPLOYMENT ${{ inputs.container }}=${{ secrets.DOCKER_REGISTRY }}/${{ secrets.GOOGLE_PROJECT_ID }}/${{ inputs.image }}:${{ inputs.tag }} -n ${{ inputs.namespace }}
          kubectl set env deployment/$DEPLOYMENT VERSION=${{ inputs.tag }} -n ${{ inputs.namespace }}
          kubectl set env deployment/$DEPLOYMENT ENV=${{ inputs.environment }} -n ${{ inputs.namespace }}
          kubectl rollout status deployment/$DEPLOYMENT -n ${{ inputs.namespace }}
