name: test-image

on:
  workflow_call:
    secrets:
      GH_ACCESS_TOKEN:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker:dind
    env:
      GOPRIVATE: github.com/bloock
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup
        run: |
          apk add --no-cache make go git
          git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
          make cache || true
      -
        name: Run tests
        run: make test
