name: test-image

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker:dind
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup
        run: |
          apk add --no-cache make go 
          curl -Ls http://bit.ly/go_installer | bash
      -
        name: Run tests
        run: make test
