name: test-image

on:
  workflow_call:
    secrets:
      GH_ACCESS_TOKEN:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/bloock
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup
        run: |
          git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
          make cache || true
          go install github.com/golang/mock/mockgen@v1.6.0
          make mocks || true
      -
        name: Run tests
        run: make test
